[package]
name = "lx"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.4", features = ["derive"] }
colored = "2"
libc = "0.2.177"
terminal_size = "0.3"
unicode-width = "0.2.2"
